### ISSUE TITLE
Test fails in Knora for know

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/Ontologies#2]
Dear Hans,
I have implemented the test and it fails because of the following reason:
https://travis-ci.org/dhlab-basel/Knora/jobs/358338037#L1768
```
Caused by: org.knora.webapi.TriplestoreResponseException: Unable to load file _test_data/other.v1.NieIneV1Spec/admin-data.ttl; triplestore responded with HTTP code 500 Internal Server Error: org.eclipse.rdf4j.repository.RepositoryException: org.eclipse.rdf4j.sail.SailException: com.ontotext.trree.consistency.ConsistencyException: Consistency check max_cardinality_1_without_deletion_flag_2 failed:
http://rdfh.ch/projects/00FF http://www.knora.org/ontology/knora-base#projectDescription "A demo project of a collection of images"^^<http://www.w3.org/2001/XMLSchema#string>
http://www.knora.org/ontology/knora-base#projectDescription http://www.w3.org/2000/01/rdf-schema#subPropertyOf http://www.knora.org/ontology/knora-base#objectCannotBeMarkedAsDeleted
http://rdfh.ch/projects/00FF http://www.knora.org/ontology/knora-base#projectDescription _:node8260
http://rdfh.ch/projects/00FF http://www.knora.org/ontology/knora-base#projectDescription "A demo project of a collection of images"@en
```

Would you mind checking if this error happens at your local test procedure? Otherwise I will update the Docker image for Knora and check if it happens there locally. If it does not, I will ask the dhlab why this is not working..

Thank you and best regards,
Jan

**Comment by hanscools** [comment]
At first glance this is all DHL stuff. AFAIK I didn't instigate any problem there. Locally everything is OK, i.e. with the bit older version. So I go for your alternative, tx.

**Comment by janCstoffregen** [comment]
Hi Hans,
ok, I'll take it from here then.

Thanks and best regards,
Jan

**Comment by janCstoffregen** [comment]
I'll document how I got to the solution afterwards.
